# Generated by Django 6.0.4 on 2026-05-02 00:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('parking_plein', 'Parking Plein'), ('sensor_defaillant', 'Sensor Defaillant')], max_length=30)),
                ('entite_id', models.IntegerField()),
                ('entite_type', models.CharField(choices=[('barriere', 'Barriere'), ('sensor', 'Sensor')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('vue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('defaillant', 'Defaillant')], default='actif', max_length=20)),
                ('derniere_lecture', models.DateTimeField(auto_now=True)),
                ('valeur', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_place', models.CharField(choices=[('standard', 'Standard'), ('handicap', 'Handicap'), ('VIP', 'VIP')], default='standard', max_length=20)),
                ('prix_heure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupee'), ('reservee', 'Reservee')], default='libre', max_length=20)),
                ('id_sensor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.sensor')),
                ('tarif_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barriere_id', models.IntegerField(default=1)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expiree'), ('annulee', 'Annulee')], default='active', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.place')),
                ('utilisateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarif_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut_paiement', models.CharField(choices=[('paye', 'Paye'), ('en_attente', 'En Attente')], default='en_attente', max_length=20)),
                ('reservation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.reservation')),
            ],
        ),
    ]
